### ISSUE TITLE
编译一下，加个图

### ISSUE THREAD

**Issue by ScienceZone** [COMOCO-5672/WindowsOnTop#1]
请将程序编译下，可以直接下载使用；麻烦将软件界面截图加上，大家好一目了然看到长啥样，希望有界面，可以使用鼠标选择置顶窗口的那种，而不是只能用快捷键，快捷键对不习惯记忆快捷键的用户很不友好，谢谢！

**Comment by COMOCO-5672** [comment]
本项目窗口置顶功能是将window窗口置顶，并不局限于本应用，可以是一个任务管理器窗口，也可以是浏览器窗口，只要没有快捷键冲突。有冲突的可以通过修改源码进行编译。本项目所有依赖项都上传，编译后即可运行，不会对外提供已编译版本。
